version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:16.9.8-ee.0'
    container_name: 'gitlab-pvehome'
    restart: always
    hostname: 'gitlab.pve.home'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.pve.home'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'mail.pve.home'
        gitlab_rails['smtp_user_name'] = 'gitlab'
        gitlab_rails['smtp_password'] = 'gitlab'
        gitlab_rails['smtp_domain'] = 'pve.home'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_authentication'] = 'plain'
        gitlab_rails['gitlab_email_from'] = 'gitlab@mail.pve.home'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@mail.pve.home'
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = {
          'main' => {
            'label' => 'LDAP',
            'host' => 'ldap.pve.home',
            'port' => 389,
            'uid' => 'uid',
            'bind_dn' => 'CN=admin,OU=people,DC=pve,DC=home',
            'password' => "$LDAP_PASSWORD",
            'encryption' => 'plain',
            'verify_certificates' => false,
            'timeout' => 10,
            'active_directory' => false,
            'user_filter' => '',
            'base' => 'dc=pve,dc=home',
            'lowercase_usernames' => 'false',
            'retry_empty_results_with_codes' => [80],
            'allow_username_or_email_login' => true,
            'block_auto_created_users' => false
          }
        }
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/config'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'